#pragma once

enum
{
	EXE_ERR_DLL_PATH_ERROR = 10001,
	EXE_ERR_UNSUPPORTED_ARCH,
	EXE_ERR_VIRTUAL_ALLOC,
	EXE_ERR_WRITE_PROC_MEM,
	EXE_ERR_CREATE_REMOTE_THREAD,
	EXE_ERR_FROZEN,
	EXE_ERR_WAIT_FOR_THREAD,
	EXE_ERR_READ_PROC_MEM,

	INJ_ERR_BEFORE_RUN = 20001,
	INJ_ERR_BEFORE_ENUM_IMPORTS,
	INJ_ERR_ENUM_IMPORTS,
	INJ_ERR_BEFORE_GETMODULEHANDLE,
	INJ_ERR_GETMODULEHANDLE,
	INJ_ERR_BEFORE_LOADLIBRARY,
	INJ_ERR_LOADLIBRARY,
	INJ_ERR_BEFORE_GETPROCADDR,
	INJ_ERR_GETPROCADDR,
	INJ_ERR_BEFORE_LIBINIT,
	LIB_ERR_INIT_ALREADY_CALLED,
	LIB_ERR_MINHOOK_FAILED,
};

typedef struct tagLOAD_LIBRARY_REMOTE_DATA {
	union {
		void* pVirtualFree;
		DWORD64 dw64VirtualFree; // make sure 32-bit/64-bit layouts are the same
	};
	WCHAR szDllName[MAX_PATH];
	DWORD dwError;
} LOAD_LIBRARY_REMOTE_DATA;

DWORD DllInject(HANDLE hProcess, HINSTANCE hDllInst, DWORD dwTimeout);
